### PR TITLE
bug(pokemon-types):set the Pokémon type to a specific spot on the page when on mobile

### LINKED ISSUE #118: Mobile Pokémon Type misplacement
**Is your feature request related to a problem? Please describe.**
All the Pokemon's type badges are misaligned and look weird.

**Describe the solution you'd like**
For the Pokemon type badges to be in their correct position in the app

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Change the placements of the Pokémon types

## Purpose
So the Pokémon types look better on mobile

## Approach
Setting the Pokémon types to a fixed position when the app is on mobile

Closes #118

### CODE REVIEW

**Review by JayDampitan — APPROVED** [review]
Easy css fix. Looks nice!

**Review by BlackCubes — APPROVED** [review]
Noice!

**Review by Wolftownn — APPROVED** [review]
Great job Luis!

**Review by krferrell — APPROVED** [review]
Looking good!

**Pull request merged**
