### PR TITLE
feat(pokemon-evolution): change parameter name for getEvolutionChain …

### LINKED ISSUE #23: Display Pokemon's Evolution Chain
**Is your feature request related to a problem? Please describe.**
The problem is simple: The evolution chain component is not being imported and rendered onto App.js.

**Describe the solution you'd like**
The solution would be to import and render PokemonEvolutions.js component onto App.js, and fix any potential stylings along the way.

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Change parameter name for getEvolutionChain in api.js.
2. Imported and rendered PokemonEvolutions component in App.js.
3. Create another async function to fulfil the evolution api with useEffect in App.js.
4. Change the positioning of the evolution component in App.css.

## Purpose
The problem was to render the evolution chain of the selected pokemon, and change some of its positioning on the screen.

## Approach
This change addresses the problem of showing the selected pokemon's evolution chain to the user.

Closes #23

### CODE REVIEW

**Review by Wolftownn — APPROVED** [review]
Looks great Elias!

**Review by Lap343 — APPROVED** [review]
Nice. Saw it when the app was open and it is coming together great!

**Review by dannysanchez559 — COMMENTED** [review]
nice

**Review by Gjhnsn — COMMENTED** [review]
Looks great!

**Pull request merged**
