### PR TITLE
Custom Audio Hook

### LINKED ISSUE #103: Create Custom Audio useHook
**Is your feature request related to a problem? Please describe.**
The audio functionalities could be refactored into a custom hook.

**Describe the solution you'd like**
Set any audio functionalities being used in `ThemeSongs.js` and `PokemonCrys.js` into a custom hook to be reused.

### PR DESCRIPTION
**Pull request by BlackCubes**
## Changes
1. Created a custom hook called `useAudio` which reduces and refactories any audio functionalities from `ThemeSongs.js` and `PokemonCry.js`.

## Purpose
The audio functionalities from `ThemeSongs.js` and `PokemonCry.js` has repeatable code. Reduce this by creating a custom hook.

## Approach
To eliminate the repeatable code in `ThemeSongs.js` and `PokemonCry.js` on implementing the audio is to create a custom hook called `useAudio` which extracts and uses `audioRef` and `audioPlay` from the two components. This helps to ensure a cleaner code and better reusability.

## Screenshots
We meet again, Reactoads

Closes #103

### CODE REVIEW

**Review by Lap343 — APPROVED** [review]
Those custom hooks and comments tho

**Review by kmausolf — APPROVED** [review]
This is so rad!  Good idea making this a hook!

**Review by Gjhnsn — APPROVED** [review]
Very clean and great comments!

**Review by Wolftownn — APPROVED** [review]
Great job on this issue as always. Thank you for writing comments in that make the code easier to read and understand!

**Pull request merged**
